<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\Schema;

/*
    Writes the data dictionary and the entity relationship diagram from the
    live schema, so the appendices in the paper cannot drift from the
    database. Run against any migrated database:

        php artisan kaya:document-schema ../docs

    Produces appendix-data-dictionary.md (every table, every column) and
    appendix-erd.md (a Mermaid erDiagram built from the foreign keys).
*/
class DocumentSchema extends Command
{
    protected $signature = 'kaya:document-schema {dir=../docs : Where to write the two files}';

    protected $description = 'Write the data dictionary and ERD from the current schema';

    /** Framework tables that are not part of the system's own design. */
    private const SKIP = [
        'migrations', 'cache', 'cache_locks', 'jobs', 'job_batches', 'failed_jobs',
        'sessions', 'password_reset_tokens', 'personal_access_tokens',
    ];

    public function handle(): int
    {
        $dir = rtrim($this->argument('dir'), '/');
        if (! is_dir($dir)) {
            mkdir($dir, 0777, true);
        }

        $tables = collect(Schema::getTables())
            ->pluck('name')
            ->reject(fn ($t) => in_array($t, self::SKIP, true))
            ->sort()
            ->values();

        $dictionary = "# Appendix: Data Dictionary\n\n";
        $dictionary .= "Every table in the KAYA database as migrated, with each column's type, whether it may be null, and its default. Generated from the schema by `php artisan kaya:document-schema`.\n\n";

        $erd = "# Appendix: Entity Relationship Diagram\n\n";
        $erd .= "Built from the foreign keys in the schema. Generated by `php artisan kaya:document-schema`.\n\n```mermaid\nerDiagram\n";

        $relations = [];

        foreach ($tables as $table) {
            $columns = Schema::getColumns($table);
            $foreign = Schema::getForeignKeys($table);
            $fkColumns = [];
            foreach ($foreign as $fk) {
                foreach ($fk['columns'] as $i => $col) {
                    $fkColumns[$col] = $fk['foreign_table'] . '.' . ($fk['foreign_columns'][$i] ?? 'id');
                    if (! in_array($fk['foreign_table'], self::SKIP, true)) {
                        $relations[] = sprintf('    %s ||--o{ %s : "%s"', $fk['foreign_table'], $table, $col);
                    }
                }
            }

            $dictionary .= "## {$table}\n\n";
            $dictionary .= "| Column | Type | Null | Default | Notes |\n|---|---|---|---|---|\n";

            $erd .= "    {$table} {\n";
            foreach ($columns as $c) {
                $notes = [];
                if ($c['name'] === 'id' && $c['auto_increment']) {
                    $notes[] = 'primary key';
                }
                if (isset($fkColumns[$c['name']])) {
                    $notes[] = 'references ' . $fkColumns[$c['name']];
                }
                $default = $c['default'] === null ? '' : str_replace('|', '\\|', (string) $c['default']);
                $dictionary .= sprintf(
                    "| %s | %s | %s | %s | %s |\n",
                    $c['name'],
                    $c['type'],
                    $c['nullable'] ? 'yes' : 'no',
                    $default,
                    implode(', ', $notes),
                );

                $mark = $c['name'] === 'id' ? ' PK' : (isset($fkColumns[$c['name']]) ? ' FK' : '');
                $erd .= sprintf("        %s %s%s\n", preg_replace('/[^a-z0-9_]/i', '_', $c['type_name']), $c['name'], $mark);
            }
            $erd .= "    }\n";
            $dictionary .= "\n";
        }

        $erd .= implode("\n", array_unique($relations)) . "\n```\n";

        file_put_contents("{$dir}/appendix-data-dictionary.md", $dictionary);
        file_put_contents("{$dir}/appendix-erd.md", $erd);

        $this->info("  {$tables->count()} tables written to {$dir}/appendix-data-dictionary.md and appendix-erd.md");

        return self::SUCCESS;
    }
}
